### PR TITLE
feat: add upgrade playbook and role

### PR DESCRIPTION
**Pull request by yqlbu**
## How to run

```bash
./scripts/update https://github.com/juicity/juicity/actions/runs/5927920609
```

## Test results

image

image

image

### CODE REVIEW

**Comment by yqlbu** [comment]
> What is the warning about? Can we avoid that?

Reflected in https://github.com/juicity/ansible-juicity-install/blob/ansible_role/ansible.cfg#L3

**Comment by yqlbu** [comment]
> > What is the warning about? Can we avoid that?
> 
> Reflected in https://github.com/juicity/ansible-juicity-install/blob/ansible_role/ansible.cfg#L3

Resolved with the following values in `ansible.cfg`

```
remote_tmp=$HOME/tmp/.ansible-${USER}/tmp
```

Test Results:

image

**Review by kunish — APPROVED** [review]
Cool

**Comment by yqlbu** [comment]
> Feel free to merge it as you wish

Cheers.

**Pull request merged**
